#!/bin/bash

docker run -it --rm \
  --name edgex-bot-container \
  -e EDGEX_BASE_URL=https://pro.edgex.exchange \
  -e EDGEX_CONTRACT_ID=10000001 \
  -e EDGEX_GRID_LEVELS_PER_SIDE=10 \
  -e EDGEX_GRID_STEP_USD=10 \
  -e EDGEX_GRID_FIRST_OFFSET_USD=10 \
  -e EDGEX_GRID_SIZE=0.001 \
  -e EDGEX_GRID_OP_SPACING_SEC=1 \
  -e EDGEX_LEVERAGE=100 \
  -e EDGEX_POSITION_LOSSCUT_PERCENTAGE=100 \
  -e EDGEX_POSITION_TAKE_PROFIT_PERCENTAGE=5.0 \
  -e EDGEX_BALANCE_RECOVERY_ENABLED=true \
  -e EDGEX_INITIAL_BALANCE_USD=409.9042 \
  -e EDGEX_RECOVERY_ENFORCE_LEVEL_USD=10.0 \
  -e EDGEX_ASSET_LOSSCUT_PERCENTAGE=30.0 \
  -e EDGEX_ASSET_TAKE_PROFIT_PERCENTAGE=50.0 \
  -e EDGEX_ACCOUNT_ID=${EDGEX_ACCOUNT_ID} \
  -e EDGEX_STARK_PRIVATE_KEY=${EDGEX_STARK_PRIVATE_KEY} \
  -v $(pwd)/logs:/app/logs \
  edgex-bot