#!/bin/bash

export EDGEX_BASE_URL=https://pro.edgex.exchange
export EDGEX_CONTRACT_ID=10000001
export EDGEX_GRID_LEVELS_PER_SIDE=6
export EDGEX_GRID_STEP_USD=60
export EDGEX_GRID_FIRST_OFFSET_USD=60
export EDGEX_GRID_SIZE=0.001
export EDGEX_GRID_OP_SPACING_SEC=1.5
export EDGEX_ACCOUNT_ID=${EDGEX_ACCOUNT_ID}
export EDGEX_STARK_PRIVATE_KEY=${EDGEX_STARK_PRIVATE_KEY}

uv run run_edgex_grid.py